export const SCATTER_POINT_SIZE = 3
export const SCATTER_POINT_SIZE_FOR_NESTING = 30
export const SCATTER_POINT_OPACITY = 1
export const SCATTER_POINT_STROKE = "black"
export const SCATTER_POITN_STROKE_WIDTH = 0